---

- name: main | Install required packages
  apt:
    name: nginx
    state: latest
  tags:
    - nginx

- name: main | Remove default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - nginx

- name: "main | UFW: allow HTTP"
  ufw:
    rule: allow
    name: 'Nginx HTTP'
  tags:
    - nginx

- include: ssl.yml
- include: configure.yml
